# Include the root Terragrunt configuration
include "root" {
  path = find_in_parent_folders("terragrunt.hcl")
}

# Generate main.tf that uses for_each to deploy all VMs
generate "main" {
  path      = "main.tf"
  if_exists = "overwrite_terragrunt"
  contents  = <<EOF
# This file is auto-generated by Terragrunt
# It uses for_each to deploy multiple VMs from the vms map

module "vms" {
  source = "../../modules/vm"

  for_each = var.vms

  # VM Configuration
  node        = each.value.node
  count       = each.value.count
  vmid_start  = each.value.vmid_start
  name        = each.value.name
  description = try(each.value.description, "")

  # VM Resources
  cpu     = try(each.value.cpu, 2)
  memory  = try(each.value.memory, 4096)
  disk_gb = try(each.value.disk_gb, 32)

  # Storage
  disk_storage = try(each.value.disk_storage, "local-lvm")
  disk_format  = try(each.value.disk_format, "raw")

  # Template/Clone
  template   = try(each.value.template, null)
  full_clone = try(each.value.full_clone, true)

  # Network
  network_bridge = try(each.value.network_bridge, "vmbr0")
  network_model  = try(each.value.network_model, "virtio")

  # Cloud-init
  ciuser     = try(each.value.ciuser, "ubuntu")
  cipassword = try(each.value.cipassword, "")
  ipconfig0  = try(each.value.ipconfig0, "ip=dhcp")
  sshkeys    = try(each.value.sshkeys, "")
  nameserver = try(each.value.nameserver, "")
  searchdomain = try(each.value.searchdomain, "")

  # Other settings
  tags     = try(each.value.tags, [])
  onboot   = try(each.value.onboot, false)
  vm_state = try(each.value.vm_state, "running")
  agent    = try(each.value.agent, 1)
}
EOF
}

# Generate variables.tf for the vms map
generate "variables" {
  path      = "variables.tf"
  if_exists = "overwrite_terragrunt"
  contents  = <<EOF
# This file is auto-generated by Terragrunt

variable "vms" {
  description = "Map of VM definitions to deploy"
  type = map(object({
    count       = number
    node        = string
    vmid_start  = number
    name        = string
    description = optional(string, "")
    cpu         = optional(number, 2)
    memory      = optional(number, 4096)
    disk_gb     = optional(number, 32)
    disk_storage = optional(string, "local-lvm")
    disk_format  = optional(string, "raw")
    template     = optional(string)
    full_clone   = optional(bool, true)
    network_bridge = optional(string, "vmbr0")
    network_model  = optional(string, "virtio")
    ciuser        = optional(string, "ubuntu")
    cipassword    = optional(string, "")
    ipconfig0    = optional(string, "ip=dhcp")
    sshkeys      = optional(string, "")
    nameserver   = optional(string, "")
    searchdomain = optional(string, "")
    tags         = optional(list(string), [])
    onboot       = optional(bool, false)
    vm_state     = optional(string, "running")
    agent        = optional(number, 1)
  }))
}
EOF
}

# Rack-specific VM definitions
inputs = {
  vms = {
    "test-vm-pvemiddle" = {
      count      = 1
      node       = "pvemiddle"
      vmid_start = 400
      name       = "test-vm-pvemiddle"
      cpu        = 2
      memory     = 4096
      disk_gb    = 32
      template   = "local:vztmpl/ubuntu-22.04-cloudinit-template"
      ciuser     = "solomon"
      ipconfig0  = "ip=dhcp"
      tags       = ["rack=middle", "environment=test"]
      onboot     = false
    }
  }
}
